# Generated by Django 6.0 on 2025-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='intensity',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='patterns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='physical_effect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='plan_to_do',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='preferred_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='related_people',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='self_view_effect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='trigger',
            field=models.TextField(blank=True),
        ),
    ]
